elasticsearch:
  host: "es.example.org"
  log: trace
index:
  name: mystuff
  type: object
users:
  - { username: testuser, password: changeme, email: "testuser@example.com" }
owner:
  name: "Your Name"
  email: "your-email@example.org"
app:
  name: "IFTTT-Elasticsearch"
session:
  secret: verysecretsessionkey