elasticsearch:
  host: "es.example.org"
  log: trace
index:
  name: ifttt
  type: common
users:
  - { username: testuser, password: changeme, email: "testuser@example.com" }
owner:
  name: "Your Name"
  email: "your-email@example.org"
app:
  name: "IFTTT-Elasticsearch"
  ui:
    github:
      enable: true
      repository: "magdev/ifttt-elasticsearch"
session:
  secret: verysecretsessionkey